// Define reusable instructions
const baseInstructions = [
  "Translate to French.",
  "Strictly translate; no commentary, no additional formatting",
  "Keep HTML tags explicitly (do not turn them into markdown), except spans which you can remove.",
  "Never add formatting (such as <i> or <b> tags) outside the existing HTML tags.",
  "Translate in the most direct, simple way possible.",
  "Always use curved apostrophes (’), not straight apostrophes.",
  "Always use nonbreakable spaces before question marks (?), colons (:), semicolons (;) and exclamation marks (!).",
];

const glossary = [
  ["path", "chemin"],
  ["course", "module"],
  ["instructor", "référent"],
  ["path session", "session de chemin"],
  ["score", "score"],
  ["published posts", "messages publiés"],
  ["coach", "animateur"],
  ["platform admins", "administrateurs plateforme"],
  ["project lead", "responsable de projet"],
  ["classroom slot", "créneau de classe"],
  ["check-in", "émarger"],
  ["manager", "manager"],
  ["dashboard", "tableau de bord"],
  ["video pitch", "enregistrement vidéo"],
  ["screencast demo", "enregistrement d’écran"],
  ["academy", "académie"],
  ["achievement", "trophées"],
  ["active member", "utilisateur actif"],
  ["activity", "activité"],
  ["account executive", "responsable Commercial(e)"],
  ["adaptative learning", "adaptative learning"],
  ["advanced roles", "rôles avancés"],
  ["ai-powered", "par l’IA"],
  ["answer correction", "corrections"],
  ["assesment", "évaluation"],
  ["at scale", "à grande échelle"],
  ["authoring tool", "outil auteur"],
  ["auto-registration", "auto-inscription"],
  ["auto-tagging", "tagging automatisé"],
  ["subtitles", "sous-titres (vidéo)"],
  ["transcripts", "sous-titres (vidéo)"],
  ["blended learning", "blended learning"],
  ["block", "bloc"],
  ["bookmark", "signet"],
  ["career paths", "évolution de carrière"],
  ["skills paths", "évolution de carrière"],
  ["career and skills paths", "évolution de carrière"],
  ["certificate expiration alert", "alertes d’expiration automatisées"],
  ["certificate", "certificat"],
  ["cheat sheet", "fiche"],
  ["classroom", "classe"],
  ["classroom dashboard", "tableau de bord de classe"],
  ["co-authored", "co-créé(e)"],
  ["co-authoring", "co-création"],
  ["co-author", "co-auteur"],
  ["coaching", "coaching"],
  ["collaborative learning", "apprentissage collaboratif"],
  ["community", "communauté"],
  ["completion rate", "taux de complétion"],
  ["content integrations", "intégrations de contenus"],
  ["course authoring", "création de formation"],
  ["course dashboard", "tableau de bord de module"],
  ["evaluation mode", "mode évaluation"],
  ["learning mode", "mode formation"],
  ["training mode", "mode entraînement"],
  ["course optionality", "module facultatif"],
  ["course template", "modèle de module"],
  ["criteria-based assessment", "critère d’évaluation"],
  ["custom field", "champ personnalisé"],
  ["custom integration", "intégration personnalisée"],
  ["custom mobile app", "appli / application mobile customisée"],
  ["custom reporting", "rapports personnalisés"],
  ["custom template", "modèle personnalisé"],
  ["customization", "personnalisation"],
  ["customized newsfeed", "fil de discussion intelligent"],
  ["discussion forum", "forum"],
  ["forum", "forum"],
  ["edit", "éditer"],
  ["enablement", "activation"],
  ["engagement rate", "taux d’engagement"],
  ["expert enablement", "formation des experts"],
  ["feedback inbox", "centre des retours"],
  ["file imports", "documents natifs"],
  ["fill-in-the-blank", "texte à trous"],
  ["group coach", "animateur de groupe"],
  ["group dashboard", "tableau de bord de groupe"],
  ["group-level authoring", "auteur de groupe"],
  ["hcm integrations", "connecteurs SIRH"],
  ["instructor-led training", "formation en présentiel"],
  ["internal comment", "commentaire interne"],
  ["just-in-time learning", "apprentissage juste-à-temps"],
  ["knowledge check", "contrôle des connaissances"],
  ["knowledge engineering", "ingénieurie des connaissances"],
  ["l&d", "département formation"],
  ["l&d manager", "responsable de la formation"],
  ["leaderboard", "classement des champions"],
  ["learning in the flow of work", "apprentissage en situation de travail"],
  ["learning need", "besoin de formation"],
  ["lifelong learning", "formation en continu"],
  ["linker", "association"],
  ["live training", "formation synchrone"],
  ["magic link", "auto-inscription sécurisée"],
  ["managee", "utilisateur managé"],
  ["manager dashboard", "tableau de bord manager"],
  ["mobile advanced", "mobile advanced"],
  ["multi-domain", "multi-domaine"],
  ["multiple choice", "question à choix multiple"],
  ["nested group", "hiérarchie des groupes"],
  ["new joiner", "nouvelle recrue"],
  ["new hire", "nouvelle recrue"],
  ["newsfeed", "fil d’actualité"],
  ["off-the-shelf content provider", "fournisseur de contenu sur étagère"],
  ["off-the-shelf course", "formations sur étagère"],
  ["offline mode", "mode hors-ligne"],
  ["onboarding", "onboarding"],
  ["ongoing program", "formation en cours"],
  ["online course", "formation en ligne"],
  ["open registration", "inscription ouverte"],
  ["open-ended", "question ouverte"],
  ["opinion", "sondage"],
  ["ordered", "question ordonnée"],
  ["participant", "participant"],
  ["participation rate", "taux de participation"],
  ["pass rate", "taux de certificats obtenus"],
  ["path linearity", "chemins linéaires"],
  ["permission", "rôle"],
  ["pick-a-point", "zone sensible"],
  ["program", "parcours"],
  ["project collaboration", "collaboration sur un projet"],
  ["project management", "gestion de projet"],
  ["project tool", "outil de gestion de projet"],
  ["projects", "outil de gestion de projet"],
  ["push notification", "notification push"],
  ["reaction score", "score des réactions"],
  ["reaction", "réaction"],
  ["registered member", "utilisateur inscrit"],
  ["relative due date", "date relative"],
  ["relevance score", "score de pertinence"],
  ["report download", "export CSV"],
  ["review", "relecture"],
  ["reviewer", "relecteur"],
  ["sales enablement", "sales enablement ou formation commerciale"],
  ["scorm compliance", "compatibilité SCORM"],
  ["screencast demo", "démo via enregistrement"],
  ["self-registration", "inscription autonome"],
  ["session instructor", "référent d’une session"],
  ["single selection", "question à choix unique"],
  ["smes (subject matter experts)", "experts métiers"],
  ["soft skills", "compétences sociales / relationnelles"],
  ["software training", "formation aux outils"],
  ["solution architect", "architecte solution"],
  ["stakeholder", "intervenant"],
  ["time-to-productivity", "temps de prise en main"],
  ["upskilling", "montée en compétences"],
  ["upvote", "vote"],
  ["user admin", "administration des utilisateurs"],
  ["user management", "gestion des utilisateurs"],
  ["user provisioning", "import utilisateurs"],
  ["user sync", "synchronisation utilisateurs"],
  ["validated program", "formation validée"],
  ["video recording", "enregistrement vidéo"],
  ["web based file", "document web"],
  ["shared mode", "mode partagé"]
];

// Build glossary instructions automatically
const glossaryInstructions = glossary.map(
  ([source, target]) => `Always translate '${source}' to '${target}'.`
);

// Function to create prompt
export const createPrompt = (question) => {
  const allInstructions = [...baseInstructions, ...glossaryInstructions];
  return `${allInstructions.join(" ")}\n\nText:\n${question}`;
};
